### ISSUE TITLE
No function to get sessionId

### ISSUE THREAD

**Issue by satya-p91** [LaurenceGA/kwamp#19]
There is no method to get sessionId of the connected session. Please add the method

**Comment by LaurenceGA** [comment]
Thanks for raising an issue!

Pull requests are welcome!

You mean you want to get a client's connected session ID from the client itself?

What's the use case for this? At the moment he session ID is mainly used internally by the router to maintain state. The client doesn't really do anything with it.

**Comment by LaurenceGA** [comment]
Since there hasn't been any further response, I'm going to close this issue. Feel free to reopen if needed.
