### ISSUE TITLE
No method found to get sessionId on the client

### ISSUE THREAD

**Issue by chukzeeman** [LaurenceGA/kwamp#22]
I cannot find any method to get session id. Please add it.
I my case I need to send the session Id to the backend to take some appropriate action

**Comment by satya-p91** [comment]
I have created a pull request regarding this if it's accepted by @LaurenceGA  you can clone the latest changes from here or you can visit https://github.com/satya-p91/kwamp

**Comment by LaurenceGA** [comment]
Thanks for the PR @satya-p91, I'll take a look!

@chukzeeman thanks for specifying your use case. I guess that could be a reasonable use case :thinking: 
Is your use case not accommodated for by the WAMP protocol itself in any other way? It does have a lot of advanced features that are maybe missing...

**Comment by LaurenceGA** [comment]
📝  Released in [v1.0.5](https://github.com/LaurenceGA/kwamp/releases/tag/v1.0.5)

**Comment by chukzeeman** [comment]
Thanks a lot for adding the method. 

> Thanks for the PR @satya-p91, I'll take a look!
> 
> @chukzeeman thanks for specifying your use case. I guess that could be a reasonable use case 
> Is your use case not accommodated for by the WAMP protocol itself in any other way? It does have a lot of advanced features that are maybe missing...
> 
>  Duplicate of #19 (probably better to re-open the issue instead of making a new one next time)

In my use case there is no easy way to achieve what  i want if i cannot know the session id of the user in the client end. I need to send the session id to the server to take appropriate action. Other wamp libs i have used provide a way to get the session id. I switched from autobahn-java to kwamp only to find out that kwamp does not have a method to get the session id.  I was a bit disappointed. I had to find an ugly workaround to achieved what i want.

Anyways. Thanks for adding the method. I appreciate. Am dropping the workaround now.

**Comment by LaurenceGA** [comment]
@chukzeeman I see... well, glad we could get your problem sorted 🙂
